service: jobsphere-backend

provider:
  name: aws
  region: us-east-1
  runtime: provided.al2
  environment:
    APP_ENV: production
    APP_DEBUG: false
    APP_KEY: ${env:APP_KEY}

    # Lambda writable storage
    APP_STORAGE: /tmp
    VIEW_COMPILED_PATH: /tmp/framework/views

    # Safe defaults
    CACHE_STORE: array
    SESSION_DRIVER: cookie
    LOG_CHANNEL: stderr

plugins:
  - ./vendor/bref/bref

functions:
  web:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - httpApi: '*'

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
    - '!vendor/bref/bref/tests/**'
    - 'storage/**'
    - 'bootstrap/cache/**'
