name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: front-end
        run: npm ci

      - name: Build React
        working-directory: front-end
        run: npm run build

      - name: Deploy Frontend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.jobsphere.co.ke
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: front-end/dist/
          server-dir: /public_html/
          dangerous-clean-slate: false